const assert=require('node:assert/strict');
const fs=require('node:fs');
const {JSDOM}=require('jsdom');
const html=fs.readFileSync(__dirname+'/../index.html','utf8');
const moduleText=fs.readFileSync(__dirname+'/../norwood-beams.js','utf8');
const dom=new JSDOM(html.replace(/<script\b[^>]*>[\s\S]*?<\/script>/gi,''),{url:'https://example.test',runScripts:'outside-only'});
const w=dom.window;
const vm=require('node:vm');
const run=s=>vm.runInContext(s,dom.getInternalVMContext());
function fn(name){const start=html.indexOf('function '+name+'(');assert.ok(start>=0,name);return html.slice(start,html.indexOf('\n}',start)+2);}
run("let products=[],lines=[],selProd=null,manualGM=null,catFilter='All',adminCatFilter='All';");
for(const name of ['isPlywoodProduct','getCategoryGM','calcRetail','populateCatDropdown','buildCatPills','setCatFilter','setAdminFilter','onCat','onGrp','onItem','onConfig','hidePreview','showPreview','quickAdd','addLine','recalcLines'])run(fn(name));
w.imgHTML=()=>'';w.updateTiers=()=>{};w.renderCatalog=()=>{};w.renderAdmin=()=>{};w.renderLines=()=>{};w.renderSummary=()=>{};w.showPage=()=>{};
run(moduleText);w.document.dispatchEvent(new w.Event('DOMContentLoaded'));
const get=s=>run(s),el=id=>w.document.getElementById(id);
assert.equal(get('products.length'),33);assert.equal(get('products.filter(p=>p.stockStatus==="Yulee").length'),22);
assert.equal(get('products.filter(p=>p.uom==="EA").length'),10);
assert.equal(get('products.every(p=>p.onHand===null)'),true);
run(moduleText);assert.equal(get('products.length'),33);
assert.equal(el('beams-rows').children.length,33);
el('beams-stock').value='Special Order';el('beams-stock').onchange();assert.equal(el('beams-rows').children.length,11);
w.quickAdd(87008);assert.equal(el('add-btn').disabled,true);assert.equal(el('sel-cat').value,'Beams & Engineered Wood');
el('beam-length').value='16';el('qty-in').value='2';w.showPreview();
assert.equal(el('prev-cost').textContent,'Cost: $69.60 / piece');
w.addLine();assert.equal(get('lines[0].qty'),2);assert.equal(get('lines[0].cost'),69.6);assert.equal(get('lines[0].retail'),99.43);assert.match(get('lines[0].item'),/16 ft/);assert.equal(get('selProd.cost'),4.35);
el('beam-basis').value='stock';el('qty-in').value='1';w.addLine();assert.equal(get('lines[1].cost'),64.48);assert.equal(get('lines[1].blueLinxRate'),4.03);
w.quickAdd(87018);assert.equal(el('beam-length-label').style.display,'none');w.addLine();assert.equal(get('lines[2].cost'),38.76);assert.equal(get('lines[2].uom'),'EA');
w.quickAdd(87000);el('beam-length').value='0';w.addLine();assert.equal(get('lines.length'),3);
el('beam-length').value='12.5';el('qty-in').value='1.5';w.addLine();assert.equal(get('lines.length'),3);
el('qty-in').value='1';w.addLine();assert.equal(get('lines[3].cost'),42);assert.equal(get('lines[3].retail'),60);
run('manualGM=0.4');w.recalcLines();assert.equal(get('lines[3].retail'),70);
const old=w.calcRetail(7,.3,null,{category:'Lumber'});assert.equal(old,10);
run('selProd={id:1,item:"Other",cost:7,category:"Lumber",group:"Test"}');w.showPreview();assert.ok(el('beam-config').classList.contains('hidden'));
console.log('PASS: 33 rows, stock filters, native category selection, LF lengths, each pricing, both cost tiers, quantities, margin overrides, no duplicates, other categories.');
dom.window.close();
